name: Flutter Template

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  flutter:
    name: Build new project
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nix-registry
      
      - name: Instantiate template
        run: |
          nix flake new flutter_env --template ./nix-registry#flutter
          nix print-dev-env ./flutter_env > /tmp/rcfile

      - name: Create flutter project
        run: | 
          source /tmp/rcfile
          flutter create flutter_project

      - name: Build APK (Release)
        working-directory: flutter_project
        run: |
          source /tmp/rcfile
          flutter build apk --release

      - name: Build project (Android App Bundle / Release)
        working-directory: flutter_project
        run: |
          source /tmp/rcfile
          flutter build appbundle --release

      - name: Build project (Assets Bundle / Release)
        working-directory: flutter_project
        run: |
          source /tmp/rcfile
          flutter build bundle --release

      - name: Build project (Linux / Release)
        working-directory: flutter_project
        run: |
          source /tmp/rcfile
          flutter build linux --release

      - name: Build project (Web / Release)
        working-directory: flutter_project
        run: |
          source /tmp/rcfile
          flutter build web --release
